### ISSUE TITLE
Crash handling or debugging?

### ISSUE THREAD

**Issue by lahdekorpi** [WebReflection/node-worker#2]
I've ported a simple scheduler script that calls different `postMessage`s telling QML to run things.
After a day or so of use, the worker stops responding to anything and stops posting messages via a `setInterval`.

The main node-process is still running as is QML and the browser is working just fine.
It seems like the sandboxed process has either crashed or been killed. The setInterval block in the code also outputs via `console.log` and even those stop, so it probably doesn't have anything to do with the WebSocket dying.

Is there any way to debug these? Or handle potential crashes or exits on the sandboxed thread?

Or should the worker server even do some kind of keepalive checking on all the workers?

**Comment by WebReflection** [comment]
without seeing any involved code I'm not sure how much I can help.

For instance, are you creating `new NodeWorker` many times or it's one worker only?

Are you incrementally holding stuff on RAM without ever cleaning?

Are you sure there's no OS idle/freeze state involved?

Have you set an `onerror` handler in both client and server?

are you sure the operation is 100% the same over the whole day?

and so on ... I need more details, thanks

**Comment by lahdekorpi** [comment]
https://github.com/WebReflection/node-worker/blob/master/server.js#L44

Might the setInterval be causing issues? I had to add it here as it's not in the context by default.

I'm trying this now with just a simple ping-pong-script on top of the demo, just to isolate the problem.

**Comment by WebReflection** [comment]
yes, `setInterval` is missing indeed ... adding it now

**Comment by WebReflection** [comment]
regardless, I want to be able to intercept sandbox errors and notify somehow either the server or the client

**Comment by lahdekorpi** [comment]
I actually didn't have an `onerror` handler previously, added one now for my test.

**Comment by WebReflection** [comment]
So, `v0.3.0` adds support for `uncaughtException` through the client side error handler (the `onerror`)

However, you can add by your own a `process.on('uncaughtException', console.error);` in any worker you want too, in case you want to be notified on the node side as well (in console/shell/whateer that is).

Please note that the `process` is currently the same shared across all workers + node itself so you basically need only one listener on the main project.

**Comment by WebReflection** [comment]
P.S. `v0.3.1` has a quick enhancement so that you can read the worker name through the err.stack too
